version: "3"

services:
 adatbazis:
  build: adatbazis
  container_name: adatbazis
  environment:
   - MYSQL_ROOT_PASSWORD=root
  volumes:
   - "./adatbazis/adatok:/var/lib/mysql"
   - "./admin/mentes/:/mentes"
  ports:
   - "3306:3306"
  networks:
   container_halozat:
    ipv4_address: 172.20.128.10

 adatbazis-slave:
  build: adatbazis-slave
  container_name: adatbazis-slave
  environment:
   - MYSQL_ROOT_PASSWORD=root
  profiles:
   - donotstart
    
 kiadas:
  build: forras/kiadas
  container_name: kiadas
  volumes:
   - "./:/var/www"
  profiles:
   - donotstart

 csomagolas:
  build: forras/csomagolas
  container_name: csomagolas
  volumes:
   - "./:/var/www"
  profiles:
   - donotstart
  
 teamspeak_adatbazis:
    build: teamspeak/adatbazis
    container_name: teamspeak_adatbazis
    command: [ "mysqld" ]
    ports:
     - "3307:3306"
    networks:
     container_halozat:
      ipv4_address: 172.20.128.14
    volumes:
     - "./teamspeak/adatbazis/adatok:/var/lib/mysql"
     - "./admin/mentes/:/mentes"
    environment:
     - MYSQL_ROOT_PASSWORD=root

 teamspeak:
    build: teamspeak/szerver
    container_name: teamspeak
    #command: [ "/opt/ts3server/ts3server" ]
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: 172.20.128.14
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: root
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    depends_on:
     - "teamspeak_adatbazis"
    volumes:
     - "./teamspeak/szerver/adatok:/var/ts3server/files"
    networks:
     container_halozat:
      ipv4_address: 172.20.128.15

 torrent-tracker:
  build: torrent-tracker
  container_name: torrent-tracker
  ports:
   - "58371:6969"
  networks:
   container_halozat:
    ipv4_address: 172.20.128.16
    
 webszerver:
    build: webszerver
    container_name: webszerver
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - "./:/hausz"
    networks:
     container_halozat:
      ipv4_address: 172.20.128.12
    depends_on:
      - "adatbazis"

 karbantarto:
  build: karbantarto
  container_name: karbantarto
  profiles:
   - donotstart

 minecraft-server:
  build: minecraft-server
  container_name: minecraft-server
  ports:
   - "25565:25565"
   - "25566:25566"
  volumes:
   - "./minecraft-server/adatok:/minecraft"
  networks:
   container_halozat:
    ipv4_address: 172.20.128.17
  profiles:
   - donotstart

 navidrome:
  build: navidrome
  container_name: navidrome
  ports:
   - "4533:4533"
  restart: unless-stopped
  environment:
   - ND_SCANSCHEDULE=24h
   - ND_SESSIONTIMEOUT=168h
  volumes:
   - "./navidrome/adatok:/data"
   - "./navidrome/fajlok:/music:ro"
  profiles:
   - donotstart

 vaultwarden:
  build: vaultwarden
  container_name: vaultwarden
  ports:
   - "8080:80"
  restart: unless-stopped
  volumes:
   - "./vaultwarden/adatok:/data"
   - "./priv:/priv"
  environment:
   - ROCKET_TLS={certs="/priv/fullchain.pem",key="/priv/privkey.pem"}
  profiles:
   - donotstart

 pihole:
  container_name: pihole
  build: pihole
  ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "67:67/udp"
    - "80:80/tcp"
  privileged: true
  environment:
    TZ: 'Europe/Budapest'
    WEBPASSWORD: 'admin'
  cap_add:
    - NET_ADMIN
  restart: unless-stopped
  networks:
   container_halozat:
    ipv4_address: 172.20.128.18

networks:
  container_halozat:
    driver: bridge
    ipam:
     config:
      - subnet: 172.20.128.0/24