version: "3"

services:
 adatbazis:
  build: adatbazis
  container_name: adatbazis
  volumes:
   - "./:/var/www"
  environment:
   - MYSQL_ROOT_PASSWORD=root
  networks:
   container_halozat:
    ipv4_address: 172.20.128.10
    
 kiadas:
  build: forras/kiadas
  container_name: kiadas
  volumes:
   - "./:/var/www"
  
 public:
   build: public
   container_name: public
   ports:
    - "80:80"
    - "443:443"
   volumes:
    - "./:/var/www"
   networks:
    container_halozat:
     ipv4_address: 172.20.128.12
   depends_on:
    - "adatbazis"

 egyuttnezo_szerver:
   build: forras/egyuttnezo_szerver
   container_name: egyuttnezo_szerver
   ports:
    - "8090:8090"
   volumes:
    - "./:/var/www"
   networks:
    container_halozat:
     ipv4_address: 172.20.128.13
   depends_on:
    - "public"
  
 teamspeak_adatbazis:
    build: teamspeak/adatbazis
    container_name: teamspeak_adatbazis
    networks:
     container_halozat:
      ipv4_address: 172.20.128.14
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
     - "./:/var/www"

 teamspeak:
    build: teamspeak/szerver
    container_name: teamspeak
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: 172.20.128.14
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: root
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    depends_on:
     - "teamspeak_adatbazis"
    networks:
     container_halozat:
      ipv4_address: 172.20.128.15

 teszteles:
  build: teszteles
  container_name: teszteles
  depends_on:
     - "public"
  volumes:
     - "./:/var/www"
  networks:
     container_halozat:
      ipv4_address: 172.20.128.16
     
networks:
  container_halozat:
    driver: bridge
    ipam:
     config:
      - subnet: 172.20.128.0/24