version: "3"

services:
 adatbazis:
  build: adatbazis
  container_name: adatbazis
  environment:
   - MYSQL_ROOT_PASSWORD=root
  volumes:
   - "./adatbazis/adatok:/var/lib/mysql"
   - "./admin/mentes/:/mentes"
  ports:
   - "3306:3306"
  networks:
   container_halozat:
    ipv4_address: 172.20.128.10
    
 kiadas:
  build: forras/kiadas
  container_name: kiadas
  volumes:
   - "./:/var/www"

 csomagolas:
  build: forras/csomagolas
  container_name: csomagolas
  volumes:
   - "./:/var/www"

 public:
   build: public
   container_name: public
   ports:
    - "80:8080"
    - "443:4443"
   volumes:
    - "./:/var/www"
   networks:
    container_halozat:
     ipv4_address: 172.20.128.12
   depends_on:
    - "adatbazis"

 egyuttnezo_szerver:
   build: forras/egyuttnezo_szerver
   container_name: egyuttnezo_szerver
   ports:
    - "8090:8090"
   volumes:
    - "./:/var/www"
   networks:
    container_halozat:
     ipv4_address: 172.20.128.13
   depends_on:
    - "public"
  
 teamspeak_adatbazis:
    build: teamspeak/adatbazis
    container_name: teamspeak_adatbazis
    command: [ "mysqld" ]
    ports:
     - "3307:3306"
    networks:
     container_halozat:
      ipv4_address: 172.20.128.14
    volumes:
     - "./teamspeak/adatbazis/adatok:/var/lib/mysql"
     - "./admin/mentes/:/mentes"
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes

 teamspeak:
    build: teamspeak/szerver
    container_name: teamspeak
    #command: [ "/opt/ts3server/ts3server" ]
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: 172.20.128.14
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: root
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    depends_on:
     - "teamspeak_adatbazis"
    volumes:
     - "./teamspeak/szerver/adatok:/var/ts3server/files"
    networks:
     container_halozat:
      ipv4_address: 172.20.128.15

 torrent-tracker:
  build: torrent-tracker
  container_name: torrent-tracker
  ports:
   - "58371:6969"
  networks:
   container_halozat:
    ipv4_address: 172.20.128.16
    
 webszerver:
    build: webszerver
    container_name: webszerver
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - "./public:/public"
    networks:
     container_halozat:
      ipv4_address: 172.20.128.17
    depends_on:
      - "adatbazis"
     
networks:
  container_halozat:
    driver: bridge
    ipam:
     config:
      - subnet: 172.20.128.0/24