FROM rust:1.74.0 as rust

FROM rust as planner
WORKDIR /webszerver
RUN cargo install cargo-chef
COPY . .
RUN cargo chef prepare  --recipe-path recipe.json

FROM rust as cacher
WORKDIR /webszerver
COPY --from=planner /usr/local/cargo /usr/local/cargo
RUN cargo install cargo-chef
COPY --from=planner /webszerver/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

FROM rust as builder
WORKDIR /webszerver
COPY --from=cacher /usr/local/cargo /usr/local/cargo
COPY --from=cacher /webszerver/target target
COPY . .
RUN cargo build --release --bin webszerver

FROM ubuntu:22.04 as runtime
WORKDIR /webszerver
RUN echo "deb http://security.ubuntu.com/ubuntu focal-security main" >> /etc/apt/sources.list
RUN apt update 
RUN apt install -y telnet 
RUN apt install -y libssl1.1
RUN apt install -y expect
COPY --from=builder /webszerver/target/release/webszerver .
COPY check_telnet.sh .
COPY create_token.sh .
COPY list_clients.sh .
RUN chmod 777 /webszerver/webszerver
# Use these to find library dependencies:
# RUN apt install readelf
# RUN readelf -a ./webszerver | grep interpreter
EXPOSE 8080
EXPOSE 4443
ENTRYPOINT ["./webszerver"]