FROM mysql:8.0.30
RUN mkdir /telepites
WORKDIR /telepites
COPY ./telepites.sh /telepites/
COPY ./mentes_visszaallitasa.sh /telepites/
COPY ./mentes.sql /telepites/
COPY ./convert_mysql_to_mariadb.sql /telepites/