FROM ubuntu:22.04
ENV TZ=Europe/Budapest
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update

RUN apt install apache2 php8.1 letsencrypt certbot python3-certbot-apache php-mysql libapache2-mod-xsendfile telnet expect -y
RUN a2enmod rewrite
RUN a2enmod headers
RUN a2enmod ssl
RUN phpenmod mysqli
RUN sed -i '/SSLCertificateFile.*snakeoil\.pem/c\SSLCertificateFile \/var\/www\/public\/fullchain.pem' /etc/apache2/sites-available/default-ssl.conf
RUN sed -i '/SSLCertificateKeyFile.*snakeoil\.key/cSSLCertificateKeyFile \/var\/www\/public\/privkey.pem' /etc/apache2/sites-available/default-ssl.conf
RUN sed -i 's/DocumentRoot \/var\/www\/html/DocumentRoot \/var\/www\/public/' /etc/apache2/sites-available/*.conf
RUN sed -i 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf
RUN a2ensite default-ssl
RUN sed -i 's/post_max_size = 8M/post_max_size = 15M/g' /etc/php/8.1/apache2/php.ini
RUN sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 15M/g' /etc/php/8.1/apache2/php.ini

EXPOSE 80
EXPOSE 443

WORKDIR /var/www/public

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]