describe('Jelszó változtatás', () => {
    it('Mobil', () => {
        cy.viewport(320, 640)
        cy.visit(Cypress.env('domain'))
        cy.mobil_belepes()
        cy.get('#felhasznalo_doboz').contains('Jelszó megváltoztatása').and('be.visible').click()
        cy.contains('Hausz jelszó változtatás')
        cy.wait(250)
        cy.get('#jelszo_valtoztatas_doboz').contains('Add meg az adataid a jelszó megváltoztatásához').and('be.visible')
        cy.get('#jelenlegi_jelszo').and('be.visible')
        cy.get('#uj_jelszo').and('be.visible')
        cy.get('#uj_jelszo_megerosites').and('be.visible')
        cy.get('#jelszo_valtoztatas_doboz').contains('Jelszó megváltoztatása').and('be.visible')
        // Mobil: Belépés / kilépés változások
        cy.mobil_kilepes()
        cy.get('#hibaNemVagyBelepveDoboz > p').and('be.visible')
        cy.mobil_belepes()
        cy.get('#jelszo_valtoztatas_doboz').contains('Add meg az adataid a jelszó megváltoztatásához').and('be.visible')
        // Mobil: Sikeres jelszó változtatás
        cy.get('#topbar').contains('Fiók').and('be.visible')
        cy.get('#jelenlegi_jelszo').and('be.visible').type('automata_teszteles')
        // Mobil: Javaslatok változása
        cy.get('#jelszoErossegTippek').contains('⚫ Kis betű')
        cy.get('#jelszoErossegTippek').contains('⚫ Nagy betű')
        cy.get('#jelszoErossegTippek').contains('⚫ Szám')
        cy.get('#jelszoErossegTippek').contains('⚫ Különleges karakter')
        cy.get('#jelszoErossegTippek').contains('⚫ Legalább 10 karakter hosszú')
        cy.get('#jelszoErossegTippek').contains('⚫ Új jelszavak egyeznek')
        cy.get('#uj_jelszo').and('be.visible').type('uj')
        cy.get('#jelszoErossegTippek').contains('🟢 Kis betű')
        cy.get('#jelszoErossegTippek').contains('🟠 Nagy betű')
        cy.get('#jelszoErossegTippek').contains('🟠 Szám')
        cy.get('#jelszoErossegTippek').contains('🟠 Különleges karakter')
        cy.get('#jelszoErossegTippek').contains('🟠 Legalább 10 karakter hosszú')
        cy.get('#jelszoErossegTippek').contains('⚫ Új jelszavak egyeznek')
        cy.get('#uj_jelszo').and('be.visible').type('_')
        cy.get('#jelszoErossegTippek').contains('🟢 Különleges karakter')
        cy.get('#uj_jelszo').and('be.visible').type('Jelszo')
        cy.get('#jelszoErossegTippek').contains('🟢 Nagy betű')
        cy.get('#uj_jelszo').and('be.visible').type('1234')
        cy.get('#jelszoErossegTippek').contains('🟢 Szám')

        cy.get('#uj_jelszo_megerosites').and('be.visible').type('uj_Jelszo123')
        cy.get('#jelszoErossegTippek').contains('🔴 Új jelszavak egyeznek')
        cy.get('#uj_jelszo_megerosites').and('be.visible').type('4')
        cy.get('#jelszoErossegTippek').contains('🟢 Új jelszavak egyeznek')
        cy.get('#jelszo_valtoztatas_doboz').contains('Jelszó megváltoztatása').and('be.visible').click()
        cy.get('#ok_jelszo_valtoztatas_sikeres').contains('Jelszavad sikeresen meg lett változtatva').and('be.visible')
        // Mobil: Sikeres jelszó visszaváltoztatás
        cy.get('#topbar').contains('Fiók').and('be.visible')
        cy.get('#jelszovaltoztatasgomb').and('be.visible').click()
        cy.get('#jelenlegi_jelszo').and('be.visible').type('uj_Jelszo1234')
        cy.get('#uj_jelszo').and('be.visible').type('automata_teszteles')
        cy.get('#uj_jelszo_megerosites').and('be.visible').type('automata_teszteles')
        cy.get('#jelszo_valtoztatas_doboz').contains('Jelszó megváltoztatása').and('be.visible').click()
        cy.get('#ok_jelszo_valtoztatas_sikeres').contains('Jelszavad sikeresen meg lett változtatva').and('be.visible')
    })

    it('Asztali', () => {
        cy.viewport(1280, 720)
        cy.visit(Cypress.env('domain'))
        cy.belepes()
        cy.get('#felhasznalo_doboz').contains('Jelszó megváltoztatása').and('be.visible').click()
        cy.contains('Hausz jelszó változtatás')
        cy.wait(250)
        cy.get('#jelszo_valtoztatas_doboz').contains('Add meg az adataid a jelszó megváltoztatásához').and('be.visible')
        cy.get('#jelenlegi_jelszo').and('be.visible')
        cy.get('#uj_jelszo').and('be.visible')
        cy.get('#uj_jelszo_megerosites').and('be.visible')
        cy.get('#jelszo_valtoztatas_doboz').contains('Jelszó megváltoztatása').and('be.visible')
        //Mobil: Belépés / kilépés változások
        cy.kilepes()
        cy.get('#hibaNemVagyBelepveDoboz > p').and('be.visible')
        cy.belepes()
        cy.contains('Javasolt irányelvek az új jelszóhoz:').and('be.visible')
        //Mobil: Sikeres jelszó változtatás
        cy.get('#jelenlegi_jelszo').and('be.visible').type('automata_teszteles')
        cy.get('#felhasznalo_doboz').contains('automata_teszteles').and('be.visible')
        cy.get('#jelszoErossegTippek').contains('⚫ Kis betű')
        cy.get('#jelszoErossegTippek').contains('⚫ Nagy betű')
        cy.get('#jelszoErossegTippek').contains('⚫ Szám')
        cy.get('#jelszoErossegTippek').contains('⚫ Különleges karakter')
        cy.get('#jelszoErossegTippek').contains('⚫ Legalább 10 karakter hosszú')
        cy.get('#jelszoErossegTippek').contains('⚫ Új jelszavak egyeznek')
        cy.get('#uj_jelszo').and('be.visible').type('uj')
        cy.get('#jelszoErossegTippek').contains('🟢 Kis betű')
        cy.get('#jelszoErossegTippek').contains('🟠 Nagy betű')
        cy.get('#jelszoErossegTippek').contains('🟠 Szám')
        cy.get('#jelszoErossegTippek').contains('🟠 Különleges karakter')
        cy.get('#jelszoErossegTippek').contains('🟠 Legalább 10 karakter hosszú')
        cy.get('#jelszoErossegTippek').contains('⚫ Új jelszavak egyeznek')
        cy.get('#uj_jelszo').and('be.visible').type('_')
        cy.get('#jelszoErossegTippek').contains('🟢 Különleges karakter')
        cy.get('#uj_jelszo').and('be.visible').type('Jelszo')
        cy.get('#jelszoErossegTippek').contains('🟢 Nagy betű')
        cy.get('#uj_jelszo').and('be.visible').type('1234')
        cy.get('#jelszoErossegTippek').contains('🟢 Szám')
        cy.get('#uj_jelszo_megerosites').and('be.visible').type('uj')
        cy.get('#jelszoErossegTippek').contains('🔴 Új jelszavak egyeznek')
        cy.get('#uj_jelszo_megerosites').and('be.visible').type('_Jelszo1234')
        cy.get('#jelszoErossegTippek').contains('🟢 Új jelszavak egyeznek')
        cy.get('#jelszo_valtoztatas_doboz').contains('Jelszó megváltoztatása').and('be.visible').click()
        cy.get('#ok_jelszo_valtoztatas_sikeres').contains('Jelszavad sikeresen meg lett változtatva').and('be.visible')
        //Mobil: Sikeres jelszó visszaváltoztatás
        cy.get('#felhasznalo_doboz').contains('automata_teszteles').and('be.visible')
        cy.get('#jelszovaltoztatasgomb').and('be.visible').click()
        cy.get('#jelenlegi_jelszo').and('be.visible').type('uj_Jelszo1234')
        cy.get('#felhasznalo_doboz').contains('automata_teszteles').and('be.visible')
        cy.get('#jelszoErossegTippek').contains('⚫ Kis betű')
        cy.get('#jelszoErossegTippek').contains('⚫ Nagy betű')
        cy.get('#jelszoErossegTippek').contains('⚫ Szám')
        cy.get('#jelszoErossegTippek').contains('⚫ Különleges karakter')
        cy.get('#jelszoErossegTippek').contains('⚫ Legalább 10 karakter hosszú')
        cy.get('#jelszoErossegTippek').contains('⚫ Új jelszavak egyeznek')
        cy.get('#uj_jelszo').and('be.visible').type('automata')
        cy.get('#jelszoErossegTippek').contains('🟢 Kis betű')
        cy.get('#jelszoErossegTippek').contains('🟠 Nagy betű')
        cy.get('#jelszoErossegTippek').contains('🟠 Szám')
        cy.get('#jelszoErossegTippek').contains('🟠 Különleges karakter')
        cy.get('#jelszoErossegTippek').contains('🟠 Legalább 10 karakter hosszú')
        cy.get('#jelszoErossegTippek').contains('⚫ Új jelszavak egyeznek')
        cy.get('#uj_jelszo').and('be.visible').type('_teszteles')
        cy.get('#jelszoErossegTippek').contains('🟢 Különleges karakter')

        cy.get('#uj_jelszo_megerosites').and('be.visible').type('automata')
        cy.get('#jelszoErossegTippek').contains('🔴 Új jelszavak egyeznek')
        cy.get('#uj_jelszo_megerosites').and('be.visible').type('_teszteles')
        cy.get('#jelszoErossegTippek').contains('🟢 Új jelszavak egyeznek')
        cy.get('#jelszo_valtoztatas_doboz').contains('Jelszó megváltoztatása').and('be.visible').click()
        cy.get('#ok_jelszo_valtoztatas_sikeres').contains('Jelszavad sikeresen meg lett változtatva').and('be.visible')
    })
})