apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adatbazis-pvc
  namespace: hausz
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adatbazis-deployment
  namespace: hausz
  labels:
    app: adatbazis
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adatbazis
        octopusexport: OctopusExport
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
        - name: adatbazis-volume
          persistentVolumeClaim:
            claimName: adatbazis-pvc
      initContainers:
      - name: adatbazis-inicializalas
        image: 'hausz-adatbazis:latest'
        imagePullPolicy: Never
        command:
        - bash
        - "-c"
        - |
          set -ex
          cd /var/log
          mkdir mysql
          chmod 777 mysql
          cd mysql
          touch mysql-bin.log
          chmod 777 mysql-bin.log
          if [ -n "$(ls -A "/var/lib/mysql")" ]; then
              echo "Mar van inicializalva adatbazis."
          else
              MYSQL_ROOT_PASSWORD=root
              mysqld --initialize-insecure
              echo [mysqld] > /mnt/conf.d/server-id.cnf
              mkdir -p /mnt/conf.d
              echo 1 >> /mnt/conf.d/server-id.cnf
          fi
        volumeMounts:
        - name: adatbazis-volume
          mountPath: /var/lib/mysql
      containers:
        - name: adatbazis-container
          image: 'hausz_adatbazis'
          imagePullPolicy: Never
          command:
            - mysqld
          volumeMounts:
            - name: adatbazis-volume
              mountPath: /var/lib/mysql
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: "600Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: adatbazis-service
  namespace: hausz
spec:
  type: ClusterIP
  ports:
  - name: adatbazis-port
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: adatbazis
  clusterIP: "10.43.1.2"
  sessionAffinity: None