apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adatbazis-pvc
  namespace: hausz
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adatbazis-replika-pvc
  namespace: hausz
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adatbazis-deployment
  namespace: hausz
  labels:
    app: adatbazis
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adatbazis
        octopusexport: OctopusExport
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
        - name: adatbazis-volume
          persistentVolumeClaim:
            claimName: adatbazis-pvc
        - name: adatbazis-replika-volume
          persistentVolumeClaim:
            claimName: adatbazis-replika-pvc
      initContainers:
      - name: adatbazis-inicializalas
        image: 'hausz_adatbazis:latest'
        imagePullPolicy: Never
        command:
        - bash
        - "-c"
        - |
          set -ex
          if [ -n "$(ls -A "/var/lib/mysql")" ]; then
              echo "Mar van inicializalva adatbazis."
          else
              cd /var/lib/
              chmod 777 adatbazis-replika
              cd adatbazis-replika
              touch mysql-bin.log
              chmod 777 mysql-bin.log
              MYSQL_ROOT_PASSWORD=root
              mkdir -p /mnt/conf.d
              echo [mysqld] > /mnt/conf.d/server-id.cnf
              echo 1 >> /mnt/conf.d/server-id.cnf
              mysqld --initialize-insecure
              mysqld &
              sleep 10
              echo "Varakozas a mysqld folyamat indulasara (10mp)"
              mysql -u root --password="root" < /telepites/osszes.sql
          fi
        volumeMounts:
        - name: adatbazis-volume
          mountPath: /var/lib/mysql
        - name: adatbazis-replika-volume
          mountPath: /var/lib/adatbazis-replika
      containers:
        - name: adatbazis-container
          image: 'hausz_adatbazis:latest'
          imagePullPolicy: Never
          command:
            - mysqld
          volumeMounts:
            - name: adatbazis-volume
              mountPath: /var/lib/mysql
            - name: adatbazis-replika-volume
              mountPath: /var/lib/adatbazis-replika
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: "600Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: adatbazis-service
  namespace: hausz
spec:
  type: ClusterIP
  ports:
  - name: adatbazis-port
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: adatbazis
  clusterIP: "10.43.1.2"
  sessionAffinity: None