FROM ubuntu:22.04
RUN apt update
RUN apt install git docker.io docker-compose mysql-client -y
RUN apt install curl -y
WORKDIR /root
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN mv kubectl /usr/local/bin
RUN chmod 777 /usr/local/bin/kubectl
RUN mkdir -p /root/.kube
RUN touch /root/.kube/config
RUN apt install openssh-server rsync -y
RUN mkdir -p /home/csabikaa97
CMD ["/bin/bash", "-c", "service ssh start && service rsync start && tail -f /dev/null"]