FROM node:12.22.12
RUN ln -s /var/www/forras/kiadas/kiadas.js /usr/local/bin/kiadas.js
WORKDIR /var/www/forras/kiadas
RUN npm install -g typescript@4.7.4
CMD /bin/bash /var/www/forras/kiadas/osszes_kiadasa.sh